# Generated by Django 5.1.5 on 2025-02-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='categoria',
            field=models.CharField(choices=[('1ra', 'Primera'), ('2da', 'Segunda'), ('3ra', 'Tercera'), ('4ta', 'Cuarta'), ('5ta', 'Quinta'), ('6ta', 'Sexta'), ('7ma', 'Séptima'), ('8va', 'Octava')], default='8va', max_length=3),
        ),
    ]
