# Generated by Django 5.1.5 on 2025-02-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_remove_jugador_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
